const GithubActions = {
    GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED',
    GET_USER_FRIENDS_REQUEST: 'GET_USER_FRIENDS_REQUEST',
    GET_USER_FRIENDS: 'GET_USER_FRIENDS',
    GET_USER_FRIENDS_FAILED: 'GET_USER_FRIENDS_FAILED',
    DELETE_ERROR_MESSAGE: 'DELETE_ERROR_MESSAGE'
};

export default GithubActions;
